//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.CharityBoxes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TmCharityBoxCollect {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TmCharityBoxCollect() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.CharityBoxes.TmCharityBoxCollect", typeof(TmCharityBoxCollect).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string BankAccountId {
            get {
                return ResourceManager.GetString("BankAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box.
        /// </summary>
        public static string CharityBox {
            get {
                return ResourceManager.GetString("CharityBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Boxes.
        /// </summary>
        public static string CharityBoxes {
            get {
                return ResourceManager.GetString("CharityBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins Category.
        /// </summary>
        public static string CoinsCategory {
            get {
                return ResourceManager.GetString("CoinsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Date.
        /// </summary>
        public static string CollectDate {
            get {
                return ResourceManager.GetString("CollectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Number.
        /// </summary>
        public static string CollectNumber {
            get {
                return ResourceManager.GetString("CollectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Category.
        /// </summary>
        public static string MemberCategory {
            get {
                return ResourceManager.GetString("MemberCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        public static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Number.
        /// </summary>
        public static string MemberNumber {
            get {
                return ResourceManager.GetString("MemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLkpId {
            get {
                return ResourceManager.GetString("StatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SubLocation {
            get {
                return ResourceManager.GetString("SubLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box Collect.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box Collect Member.
        /// </summary>
        public static string TmCharityBoxCollectMemberId {
            get {
                return ResourceManager.GetString("TmCharityBoxCollectMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value1000Dh.
        /// </summary>
        public static string Value1000Dh {
            get {
                return ResourceManager.GetString("Value1000Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value100Dh.
        /// </summary>
        public static string Value100Dh {
            get {
                return ResourceManager.GetString("Value100Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value10Dh.
        /// </summary>
        public static string Value10Dh {
            get {
                return ResourceManager.GetString("Value10Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value1Dh.
        /// </summary>
        public static string Value1Dh {
            get {
                return ResourceManager.GetString("Value1Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value200Dh.
        /// </summary>
        public static string Value200Dh {
            get {
                return ResourceManager.GetString("Value200Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value20Dh.
        /// </summary>
        public static string Value20Dh {
            get {
                return ResourceManager.GetString("Value20Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value25F.
        /// </summary>
        public static string Value25F {
            get {
                return ResourceManager.GetString("Value25F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value500Dh.
        /// </summary>
        public static string Value500Dh {
            get {
                return ResourceManager.GetString("Value500Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value50Dh.
        /// </summary>
        public static string Value50Dh {
            get {
                return ResourceManager.GetString("Value50Dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value50F.
        /// </summary>
        public static string Value50F {
            get {
                return ResourceManager.GetString("Value50F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value5Dh.
        /// </summary>
        public static string Value5Dh {
            get {
                return ResourceManager.GetString("Value5Dh", resourceCulture);
            }
        }
    }
}
