//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.Common.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Management.
        /// </summary>
        public static string AbBank {
            get {
                return ResourceManager.GetString("AbBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Reconsilation.
        /// </summary>
        public static string AccountsReconsilation {
            get {
                return ResourceManager.GetString("AccountsReconsilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Statement.
        /// </summary>
        public static string AccountStatement {
            get {
                return ResourceManager.GetString("AccountStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee Permissions.
        /// </summary>
        public static string ActionScCommittee {
            get {
                return ResourceManager.GetString("ActionScCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Call.
        /// </summary>
        public static string ActivityCall {
            get {
                return ResourceManager.GetString("ActivityCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Meeting.
        /// </summary>
        public static string ActivityMeeting {
            get {
                return ResourceManager.GetString("ActivityMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Tasks.
        /// </summary>
        public static string ActivityTasks {
            get {
                return ResourceManager.GetString("ActivityTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank and Custodians.
        /// </summary>
        public static string ApBanks {
            get {
                return ResourceManager.GetString("ApBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr/Cr Memo.
        /// </summary>
        public static string ApDrCrHd {
            get {
                return ResourceManager.GetString("ApDrCrHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string ApInvoiceHd {
            get {
                return ResourceManager.GetString("ApInvoiceHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Payments.
        /// </summary>
        public static string ApMiscPaymentHeaders {
            get {
                return ResourceManager.GetString("ApMiscPaymentHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string ApPaymentsTransactions {
            get {
                return ResourceManager.GetString("ApPaymentsTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP PDC.
        /// </summary>
        public static string ApPdcInterface {
            get {
                return ResourceManager.GetString("ApPdcInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid Expenses.
        /// </summary>
        public static string ApPrepaid {
            get {
                return ResourceManager.GetString("ApPrepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank User Access.
        /// </summary>
        public static string ApUserBankAccess {
            get {
                return ResourceManager.GetString("ApUserBankAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string ApVendors {
            get {
                return ResourceManager.GetString("ApVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string ArCustomers {
            get {
                return ResourceManager.GetString("ArCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr/Cr Memo.
        /// </summary>
        public static string ArDrCrHd {
            get {
                return ResourceManager.GetString("ArDrCrHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string ArInvoiceHd {
            get {
                return ResourceManager.GetString("ArInvoiceHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Settlements.
        /// </summary>
        public static string ArInvoiceSettlementHd {
            get {
                return ResourceManager.GetString("ArInvoiceSettlementHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar JobCard.
        /// </summary>
        public static string ArJobCard {
            get {
                return ResourceManager.GetString("ArJobCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar JobCard Details.
        /// </summary>
        public static string ArJobCardDetails {
            get {
                return ResourceManager.GetString("ArJobCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Card.
        /// </summary>
        public static string ArJobCardHd {
            get {
                return ResourceManager.GetString("ArJobCardHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Card Payments.
        /// </summary>
        public static string ArJobCardPaymentHd {
            get {
                return ResourceManager.GetString("ArJobCardPaymentHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar Misc Receipt.
        /// </summary>
        public static string ArMiscReceiptHeaders {
            get {
                return ResourceManager.GetString("ArMiscReceiptHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR PDC.
        /// </summary>
        public static string ArPdcInterface {
            get {
                return ResourceManager.GetString("ArPdcInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Receipts.
        /// </summary>
        public static string ArReceipts {
            get {
                return ResourceManager.GetString("ArReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        public static string ArSecurityDepositInterface {
            get {
                return ResourceManager.GetString("ArSecurityDepositInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets Disposal.
        /// </summary>
        public static string AssetsDisposal {
            get {
                return ResourceManager.GetString("AssetsDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets Sales.
        /// </summary>
        public static string AssetsSales {
            get {
                return ResourceManager.GetString("AssetsSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        public static string AssistantProfessor {
            get {
                return ResourceManager.GetString("AssistantProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asssets Purchase.
        /// </summary>
        public static string AsssetsPurchase {
            get {
                return ResourceManager.GetString("AsssetsPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Reconsilation.
        /// </summary>
        public static string BankReconsilation {
            get {
                return ResourceManager.GetString("BankReconsilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank and Custodians.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Analyzer.
        /// </summary>
        public static string BudgetPerformance {
            get {
                return ResourceManager.GetString("BudgetPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Interface.
        /// </summary>
        public static string CashInterface {
            get {
                return ResourceManager.GetString("CashInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheques Delays.
        /// </summary>
        public static string ChequesDelays {
            get {
                return ResourceManager.GetString("ChequesDelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheques Deposits.
        /// </summary>
        public static string ChequesDeposits {
            get {
                return ResourceManager.GetString("ChequesDeposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheques Replacement.
        /// </summary>
        public static string ChequesReplacement {
            get {
                return ResourceManager.GetString("ChequesReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheques Returns.
        /// </summary>
        public static string ChequesReturns {
            get {
                return ResourceManager.GetString("ChequesReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheques Withdrowals.
        /// </summary>
        public static string ChequesWithdrowals {
            get {
                return ResourceManager.GetString("ChequesWithdrowals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Units.
        /// </summary>
        public static string ComplexUnits {
            get {
                return ResourceManager.GetString("ComplexUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string ContractsSub {
            get {
                return ResourceManager.GetString("ContractsSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Interface.
        /// </summary>
        public static string CreditCardInterface {
            get {
                return ResourceManager.GetString("CreditCardInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM.
        /// </summary>
        public static string CRM {
            get {
                return ResourceManager.GetString("CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        public static string CRM_Agents {
            get {
                return ResourceManager.GetString("CRM_Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD Setup.
        /// </summary>
        public static string CRM_BDSetup {
            get {
                return ResourceManager.GetString("CRM_BDSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string CRM_Contacts {
            get {
                return ResourceManager.GetString("CRM_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals.
        /// </summary>
        public static string CRM_Deals {
            get {
                return ResourceManager.GetString("CRM_Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        public static string CRM_Leads {
            get {
                return ResourceManager.GetString("CRM_Leads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string CRM_Products {
            get {
                return ResourceManager.GetString("CRM_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string CRM_Projects {
            get {
                return ResourceManager.GetString("CRM_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string CRM_Services {
            get {
                return ResourceManager.GetString("CRM_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUs.
        /// </summary>
        public static string CrmAboutUs {
            get {
                return ResourceManager.GetString("CrmAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm Contact Us.
        /// </summary>
        public static string CrmContactUs {
            get {
                return ResourceManager.GetString("CrmContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crm Deals.
        /// </summary>
        public static string CrmDeals {
            get {
                return ResourceManager.GetString("CrmDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmLeads Persons.
        /// </summary>
        public static string CrmLeadsPersons {
            get {
                return ResourceManager.GetString("CrmLeadsPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string CrmProducts {
            get {
                return ResourceManager.GetString("CrmProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string CrmProjects {
            get {
                return ResourceManager.GetString("CrmProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inquiries.
        /// </summary>
        public static string CrmQueries {
            get {
                return ResourceManager.GetString("CrmQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string CrmServices {
            get {
                return ResourceManager.GetString("CrmServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Request.
        /// </summary>
        public static string DocumentRequest {
            get {
                return ResourceManager.GetString("DocumentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Profile.
        /// </summary>
        public static string EmployeeProfile {
            get {
                return ResourceManager.GetString("EmployeeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacant units report.
        /// </summary>
        public static string EmptyPms {
            get {
                return ResourceManager.GetString("EmptyPms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineers.
        /// </summary>
        public static string Engineers {
            get {
                return ResourceManager.GetString("Engineers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets Workbench.
        /// </summary>
        public static string FaAsset {
            get {
                return ResourceManager.GetString("FaAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Asset.
        /// </summary>
        public static string FaAssetCategory {
            get {
                return ResourceManager.GetString("FaAssetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets Depreciation.
        /// </summary>
        public static string FaAssetDeprnHd {
            get {
                return ResourceManager.GetString("FaAssetDeprnHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaAssets List.
        /// </summary>
        public static string FaAssetList {
            get {
                return ResourceManager.GetString("FaAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Data.
        /// </summary>
        public static string FinanceData {
            get {
                return ResourceManager.GetString("FinanceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Assets.
        /// </summary>
        public static string FixedAssets {
            get {
                return ResourceManager.GetString("FixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FmContracts.
        /// </summary>
        public static string FmContracts {
            get {
                return ResourceManager.GetString("FmContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineers.
        /// </summary>
        public static string FmEngineers {
            get {
                return ResourceManager.GetString("FmEngineers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Execution.
        /// </summary>
        public static string FmMaintRequisitionsExe {
            get {
                return ResourceManager.GetString("FmMaintRequisitionsExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Order.
        /// </summary>
        public static string FmMaintRequisitionsHdr {
            get {
                return ResourceManager.GetString("FmMaintRequisitionsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectors.
        /// </summary>
        public static string FndCollectors {
            get {
                return ResourceManager.GetString("FndCollectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Men.
        /// </summary>
        public static string FndSalesMen {
            get {
                return ResourceManager.GetString("FndSalesMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Types.
        /// </summary>
        public static string FndTaxType {
            get {
                return ResourceManager.GetString("FndTaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Users.
        /// </summary>
        public static string FndUsers {
            get {
                return ResourceManager.GetString("FndUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding.
        /// </summary>
        public static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General UnPost.
        /// </summary>
        public static string GeneralUnPost {
            get {
                return ResourceManager.GetString("GeneralUnPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Values.
        /// </summary>
        public static string GlAccDetails {
            get {
                return ResourceManager.GetString("GlAccDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Setup.
        /// </summary>
        public static string GlAccHeaders {
            get {
                return ResourceManager.GetString("GlAccHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Analyzer.
        /// </summary>
        public static string GlAccMappingHd {
            get {
                return ResourceManager.GetString("GlAccMappingHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of Accounts.
        /// </summary>
        public static string GlAccounts {
            get {
                return ResourceManager.GetString("GlAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Statement.
        /// </summary>
        public static string GlAccSelection {
            get {
                return ResourceManager.GetString("GlAccSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Voucher.
        /// </summary>
        public static string GlJeHeaders {
            get {
                return ResourceManager.GetString("GlJeHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Journal Entries.
        /// </summary>
        public static string GlJeIntegrationHeaders {
            get {
                return ResourceManager.GetString("GlJeIntegrationHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Accounts.
        /// </summary>
        public static string GlMainAccounts {
            get {
                return ResourceManager.GetString("GlMainAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string GlPeriods {
            get {
                return ResourceManager.GetString("GlPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string GlPeriodsYears {
            get {
                return ResourceManager.GetString("GlPeriodsYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        public static string Grades {
            get {
                return ResourceManager.GetString("Grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantees.
        /// </summary>
        public static string Guarantees {
            get {
                return ResourceManager.GetString("Guarantees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Leave.
        /// </summary>
        public static string HourlyLeave {
            get {
                return ResourceManager.GetString("HourlyLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR and Payroll.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Data.
        /// </summary>
        public static string HRData {
            get {
                return ResourceManager.GetString("HRData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRMS Settings.
        /// </summary>
        public static string HRMSSettings {
            get {
                return ResourceManager.GetString("HRMSSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Structure.
        /// </summary>
        public static string HrOrganizations {
            get {
                return ResourceManager.GetString("HrOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Request.
        /// </summary>
        public static string HrPaperRequest {
            get {
                return ResourceManager.GetString("HrPaperRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string HrPersonPermission {
            get {
                return ResourceManager.GetString("HrPersonPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Document.
        /// </summary>
        public static string HrPersonRequestDocument {
            get {
                return ResourceManager.GetString("HrPersonRequestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string HrPersons {
            get {
                return ResourceManager.GetString("HrPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additions.
        /// </summary>
        public static string HrPersonsAdditionHd {
            get {
                return ResourceManager.GetString("HrPersonsAdditionHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions.
        /// </summary>
        public static string HrPersonsDeductionHd {
            get {
                return ResourceManager.GetString("HrPersonsDeductionHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Sheet.
        /// </summary>
        public static string HrPersonTimeSheet {
            get {
                return ResourceManager.GetString("HrPersonTimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves.
        /// </summary>
        public static string HrPersonVacations {
            get {
                return ResourceManager.GetString("HrPersonVacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hr Reports.
        /// </summary>
        public static string HrReports {
            get {
                return ResourceManager.GetString("HrReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves Types.
        /// </summary>
        public static string HrVacationsTypes {
            get {
                return ResourceManager.GetString("HrVacationsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Data.
        /// </summary>
        public static string InventoryData {
            get {
                return ResourceManager.GetString("InventoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Settings.
        /// </summary>
        public static string InventorySettings {
            get {
                return ResourceManager.GetString("InventorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Types.
        /// </summary>
        public static string IssueTypes {
            get {
                return ResourceManager.GetString("IssueTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Movements.
        /// </summary>
        public static string ItemMovements {
            get {
                return ResourceManager.GetString("ItemMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Adjustment.
        /// </summary>
        public static string IvAdjustmentHd {
            get {
                return ResourceManager.GetString("IvAdjustmentHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory settings.
        /// </summary>
        public static string IvInventorySetting {
            get {
                return ResourceManager.GetString("IvInventorySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Definition.
        /// </summary>
        public static string IvItems {
            get {
                return ResourceManager.GetString("IvItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Categories.
        /// </summary>
        public static string IvItemsTypesConfigure {
            get {
                return ResourceManager.GetString("IvItemsTypesConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IvPosHd.
        /// </summary>
        public static string IvPosHd {
            get {
                return ResourceManager.GetString("IvPosHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List.
        /// </summary>
        public static string IvPriceListHd {
            get {
                return ResourceManager.GetString("IvPriceListHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Receipt.
        /// </summary>
        public static string IvReceiveHd {
            get {
                return ResourceManager.GetString("IvReceiveHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Vendor.
        /// </summary>
        public static string IvReturnReceiveHd {
            get {
                return ResourceManager.GetString("IvReturnReceiveHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Return.
        /// </summary>
        public static string IvReturnSaleHd {
            get {
                return ResourceManager.GetString("IvReturnSaleHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string IvSaleHd {
            get {
                return ResourceManager.GetString("IvSaleHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Inquery.
        /// </summary>
        public static string IvSaleHdInQuery {
            get {
                return ResourceManager.GetString("IvSaleHdInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Issue.
        /// </summary>
        public static string IvStoreIssue {
            get {
                return ResourceManager.GetString("IvStoreIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string IvUnits {
            get {
                return ResourceManager.GetString("IvUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses Access.
        /// </summary>
        public static string IvUserWarehousesPrivileges {
            get {
                return ResourceManager.GetString("IvUserWarehousesPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        public static string IvWarehouses {
            get {
                return ResourceManager.GetString("IvWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Execution.
        /// </summary>
        public static string JobExecution {
            get {
                return ResourceManager.GetString("JobExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Order.
        /// </summary>
        public static string JobOrder {
            get {
                return ResourceManager.GetString("JobOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leasing.
        /// </summary>
        public static string Leasing {
            get {
                return ResourceManager.GetString("Leasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Requst.
        /// </summary>
        public static string LeaveRequst {
            get {
                return ResourceManager.GetString("LeaveRequst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookups.
        /// </summary>
        public static string Lookups {
            get {
                return ResourceManager.GetString("Lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Contracts.
        /// </summary>
        public static string MaintenanceContracts {
            get {
                return ResourceManager.GetString("MaintenanceContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Boarding.
        /// </summary>
        public static string OnBoarding {
            get {
                return ResourceManager.GetString("OnBoarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Management.
        /// </summary>
        public static string Organization_Management {
            get {
                return ResourceManager.GetString("Organization_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Settings.
        /// </summary>
        public static string OrganizationSettings {
            get {
                return ResourceManager.GetString("OrganizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments Certificate.
        /// </summary>
        public static string PaymentsCertificate {
            get {
                return ResourceManager.GetString("PaymentsCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Schedule.
        /// </summary>
        public static string PaymentSchedule {
            get {
                return ResourceManager.GetString("PaymentSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payslip.
        /// </summary>
        public static string Payslip {
            get {
                return ResourceManager.GetString("Payslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pension.
        /// </summary>
        public static string Pension {
            get {
                return ResourceManager.GetString("Pension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performa Invoice.
        /// </summary>
        public static string PerformaInvoice {
            get {
                return ResourceManager.GetString("PerformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Cancellation.
        /// </summary>
        public static string PmCancellationContracts {
            get {
                return ResourceManager.GetString("PmCancellationContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string PmContract {
            get {
                return ResourceManager.GetString("PmContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-renewed contract disclosure report.
        /// </summary>
        public static string PmContractNotRenewed {
            get {
                return ResourceManager.GetString("PmContractNotRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string PmContracts {
            get {
                return ResourceManager.GetString("PmContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Charges.
        /// </summary>
        public static string PmOtherPaymentTypes {
            get {
                return ResourceManager.GetString("PmOtherPaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners.
        /// </summary>
        public static string PmOwners {
            get {
                return ResourceManager.GetString("PmOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PmProperties {
            get {
                return ResourceManager.GetString("PmProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string PmTenants {
            get {
                return ResourceManager.GetString("PmTenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Expiration.
        /// </summary>
        public static string PmTerminateContracts {
            get {
                return ResourceManager.GetString("PmTerminateContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Sales.
        /// </summary>
        public static string PointofSales {
            get {
                return ResourceManager.GetString("PointofSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PoPurchaseOrder {
            get {
                return ResourceManager.GetString("PoPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Users.
        /// </summary>
        public static string PortalUser {
            get {
                return ResourceManager.GetString("PortalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal User Data.
        /// </summary>
        public static string PortalUserData {
            get {
                return ResourceManager.GetString("PortalUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal User Reg.
        /// </summary>
        public static string PortalUserReg {
            get {
                return ResourceManager.GetString("PortalUserReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Lists.
        /// </summary>
        public static string PriceLists {
            get {
                return ResourceManager.GetString("PriceLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Lists Access.
        /// </summary>
        public static string PriceListsAccess {
            get {
                return ResourceManager.GetString("PriceListsAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string PROJECTS {
            get {
                return ResourceManager.GetString("PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string PROJECTS_Contracts {
            get {
                return ResourceManager.GetString("PROJECTS_Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Ceriticate.
        /// </summary>
        public static string PROJECTS_Payment_Ceriticate {
            get {
                return ResourceManager.GetString("PROJECTS_Payment_Ceriticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments Certificate.
        /// </summary>
        public static string PROJECTS_Payments_Certificate {
            get {
                return ResourceManager.GetString("PROJECTS_Payments_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string PROJECTS_Projects {
            get {
                return ResourceManager.GetString("PROJECTS_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Bill of Quantities.
        /// </summary>
        public static string PROJECTS_Projects_Bill_Of_Quantities {
            get {
                return ResourceManager.GetString("PROJECTS_Projects_Bill_Of_Quantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Estimation.
        /// </summary>
        public static string PROJECTS_Projects_Estimation {
            get {
                return ResourceManager.GetString("PROJECTS_Projects_Estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Management.
        /// </summary>
        public static string PROJECTS_Projects_Management {
            get {
                return ResourceManager.GetString("PROJECTS_Projects_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Settings.
        /// </summary>
        public static string PROJECTS_Projects_Settings {
            get {
                return ResourceManager.GetString("PROJECTS_Projects_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Variations.
        /// </summary>
        public static string PROJECTS_Projects_Variations {
            get {
                return ResourceManager.GetString("PROJECTS_Projects_Variations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcontract Management.
        /// </summary>
        public static string PROJECTS_Subcontract_Management {
            get {
                return ResourceManager.GetString("PROJECTS_Subcontract_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variations.
        /// </summary>
        public static string PROJECTS_Variations {
            get {
                return ResourceManager.GetString("PROJECTS_Variations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Data.
        /// </summary>
        public static string ProjectsData {
            get {
                return ResourceManager.GetString("ProjectsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string PropertiesRevenue {
            get {
                return ResourceManager.GetString("PropertiesRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Data.
        /// </summary>
        public static string PropertyData {
            get {
                return ResourceManager.GetString("PropertyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Requesition.
        /// </summary>
        public static string PurchaseRequesition {
            get {
                return ResourceManager.GetString("PurchaseRequesition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing.
        /// </summary>
        public static string Purchasing {
            get {
                return ResourceManager.GetString("Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Elements.
        /// </summary>
        public static string PyElements {
            get {
                return ResourceManager.GetString("PyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Run.
        /// </summary>
        public static string PyPayrollOperations {
            get {
                return ResourceManager.GetString("PyPayrollOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Types.
        /// </summary>
        public static string PyPayrollTypes {
            get {
                return ResourceManager.GetString("PyPayrollTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Analysis.
        /// </summary>
        public static string QuotationAnalysis {
            get {
                return ResourceManager.GetString("QuotationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotations.
        /// </summary>
        public static string Quotations {
            get {
                return ResourceManager.GetString("Quotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string RealEstateAndEnDowment {
            get {
                return ResourceManager.GetString("RealEstateAndEnDowment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Receivables.
        /// </summary>
        public static string Receivables {
            get {
                return ResourceManager.GetString("Receivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Management.
        /// </summary>
        public static string RenewalManagement {
            get {
                return ResourceManager.GetString("RenewalManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Accounts.
        /// </summary>
        public static string ReportAccounts {
            get {
                return ResourceManager.GetString("ReportAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportPms {
            get {
                return ResourceManager.GetString("ReportPms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gl Acc Statement.
        /// </summary>
        public static string ReportsAccounts {
            get {
                return ResourceManager.GetString("ReportsAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Aids.
        /// </summary>
        public static string ReportsAids {
            get {
                return ResourceManager.GetString("ReportsAids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Sales.
        /// </summary>
        public static string ReportSales {
            get {
                return ResourceManager.GetString("ReportSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Reports.
        /// </summary>
        public static string ReportsTms {
            get {
                return ResourceManager.GetString("ReportsTms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request For Quotation.
        /// </summary>
        public static string RequestForQuotation {
            get {
                return ResourceManager.GetString("RequestForQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Per Nationality.
        /// </summary>
        public static string RequestsPerNationality {
            get {
                return ResourceManager.GetString("RequestsPerNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets Workbench.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Vendor.
        /// </summary>
        public static string ReturnToVendor {
            get {
                return ResourceManager.GetString("ReturnToVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string RolesMenu {
            get {
                return ResourceManager.GetString("RolesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rpt PyPayroll Operation Persons.
        /// </summary>
        public static string RptPyPayrollOperationPersons {
            get {
                return ResourceManager.GetString("RptPyPayrollOperationPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Profile.
        /// </summary>
        public static string SalesmanProfile {
            get {
                return ResourceManager.GetString("SalesmanProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesmen.
        /// </summary>
        public static string Salesmen {
            get {
                return ResourceManager.GetString("Salesmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        public static string SalesOrder {
            get {
                return ResourceManager.GetString("SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campains.
        /// </summary>
        public static string ScCampains {
            get {
                return ResourceManager.GetString("ScCampains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Campains Aid.
        /// </summary>
        public static string ScCampainsAid {
            get {
                return ResourceManager.GetString("ScCampainsAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Campains Deliver.
        /// </summary>
        public static string ScCampainsDetailDeliver {
            get {
                return ResourceManager.GetString("ScCampainsDetailDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases List.
        /// </summary>
        public static string SCCasesListReport {
            get {
                return ResourceManager.GetString("SCCasesListReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Comity Members.
        /// </summary>
        public static string ScComityMembers {
            get {
                return ResourceManager.GetString("ScComityMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Committee.
        /// </summary>
        public static string ScCommittee {
            get {
                return ResourceManager.GetString("ScCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Committees Check.
        /// </summary>
        public static string ScCommitteesCheck {
            get {
                return ResourceManager.GetString("ScCommitteesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScCommittees Check Report.
        /// </summary>
        public static string ScCommitteesCheckReport {
            get {
                return ResourceManager.GetString("ScCommitteesCheckReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Other Aids.
        /// </summary>
        public static string ScDeliveryOtherAids {
            get {
                return ResourceManager.GetString("ScDeliveryOtherAids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScFnd Aid Request Type.
        /// </summary>
        public static string ScFndAidRequestType {
            get {
                return ResourceManager.GetString("ScFndAidRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScFnd Portal Interval Setting.
        /// </summary>
        public static string ScFndPortalIntervalSetting {
            get {
                return ResourceManager.GetString("ScFndPortalIntervalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScFnd Protal Attachment Setting.
        /// </summary>
        public static string ScFndProtalAttachmentSetting {
            get {
                return ResourceManager.GetString("ScFndProtalAttachmentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Contract.
        /// </summary>
        public static string ScMaintenanceContract {
            get {
                return ResourceManager.GetString("ScMaintenanceContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Payments.
        /// </summary>
        public static string ScMaintenancePayments {
            get {
                return ResourceManager.GetString("ScMaintenancePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Quotations.
        /// </summary>
        public static string ScMaintenanceQuotations {
            get {
                return ResourceManager.GetString("ScMaintenanceQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Technical Report.
        /// </summary>
        public static string ScMaintenanceTechnicalReport {
            get {
                return ResourceManager.GetString("ScMaintenanceTechnicalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Portal Requests.
        /// </summary>
        public static string ScPortalRequest {
            get {
                return ResourceManager.GetString("ScPortalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Manager Decision.
        /// </summary>
        public static string ScPortalRequestMgrDecision {
            get {
                return ResourceManager.GetString("ScPortalRequestMgrDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc Request Study.
        /// </summary>
        public static string ScPortalRequestStudy {
            get {
                return ResourceManager.GetString("ScPortalRequestStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        public static string SecurityDetailsList {
            get {
                return ResourceManager.GetString("SecurityDetailsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Payables.
        /// </summary>
        public static string SelfReceivables {
            get {
                return ResourceManager.GetString("SelfReceivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Service.
        /// </summary>
        public static string SelfService {
            get {
                return ResourceManager.GetString("SelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Situations.
        /// </summary>
        public static string SocialSituations {
            get {
                return ResourceManager.GetString("SocialSituations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficents.
        /// </summary>
        public static string SpBeneficent {
            get {
                return ResourceManager.GetString("SpBeneficent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficents.
        /// </summary>
        public static string SpBeneficents {
            get {
                return ResourceManager.GetString("SpBeneficents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpCase Cancel Operation Report.
        /// </summary>
        public static string SpCaseCancelOperationReport {
            get {
                return ResourceManager.GetString("SpCaseCancelOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Edit Data.
        /// </summary>
        public static string SpCaseEditData {
            get {
                return ResourceManager.GetString("SpCaseEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsored List.
        /// </summary>
        public static string SpCaseList {
            get {
                return ResourceManager.GetString("SpCaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaseOperations.
        /// </summary>
        public static string SpCaseOperations {
            get {
                return ResourceManager.GetString("SpCaseOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Case Replace.
        /// </summary>
        public static string SpCaseOperationsReplace {
            get {
                return ResourceManager.GetString("SpCaseOperationsReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpCase Replace Operation Report.
        /// </summary>
        public static string SpCaseReplaceOperationReport {
            get {
                return ResourceManager.GetString("SpCaseReplaceOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string SpCases {
            get {
                return ResourceManager.GetString("SpCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpCase Turn Off Operation Report.
        /// </summary>
        public static string SpCaseTurnOffOperationReport {
            get {
                return ResourceManager.GetString("SpCaseTurnOffOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string SpContracts {
            get {
                return ResourceManager.GetString("SpContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee Permissions.
        /// </summary>
        public static string SpecialPermissionsManagement {
            get {
                return ResourceManager.GetString("SpecialPermissionsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpFamilies.
        /// </summary>
        public static string SpFamilies {
            get {
                return ResourceManager.GetString("SpFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpGuaranteesReports.
        /// </summary>
        public static string SpGuaranteesReports {
            get {
                return ResourceManager.GetString("SpGuaranteesReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sponsored are 18 years old.
        /// </summary>
        public static string Sponsoredare18 {
            get {
                return ResourceManager.GetString("Sponsoredare18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpPayments.
        /// </summary>
        public static string SpPayments {
            get {
                return ResourceManager.GetString("SpPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpPayment Setting.
        /// </summary>
        public static string SpPaymentSetting {
            get {
                return ResourceManager.GetString("SpPaymentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics.
        /// </summary>
        public static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Transfer.
        /// </summary>
        public static string StoreTransfer {
            get {
                return ResourceManager.GetString("StoreTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcontract Management.
        /// </summary>
        public static string SubcontractManagement {
            get {
                return ResourceManager.GetString("SubcontractManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Assign.
        /// </summary>
        public static string TemplateAssign {
            get {
                return ResourceManager.GetString("TemplateAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Account Statement .
        /// </summary>
        public static string TenantAccount {
            get {
                return ResourceManager.GetString("TenantAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string TenantData {
            get {
                return ResourceManager.GetString("TenantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string TenantModules {
            get {
                return ResourceManager.GetString("TenantModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Attendance.
        /// </summary>
        public static string TimeAttendance {
            get {
                return ResourceManager.GetString("TimeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Attendance Template.
        /// </summary>
        public static string TimeAttendanceTemplate {
            get {
                return ResourceManager.GetString("TimeAttendanceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box Actions.
        /// </summary>
        public static string TmCharityBoxActions {
            get {
                return ResourceManager.GetString("TmCharityBoxActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box Collect.
        /// </summary>
        public static string TmCharityBoxCollect {
            get {
                return ResourceManager.GetString("TmCharityBoxCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box Collect Members.
        /// </summary>
        public static string TmCharityBoxCollectMembers {
            get {
                return ResourceManager.GetString("TmCharityBoxCollectMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Boxes.
        /// </summary>
        public static string TmCharityBoxes {
            get {
                return ResourceManager.GetString("TmCharityBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Boxes Type.
        /// </summary>
        public static string TmCharityBoxesType {
            get {
                return ResourceManager.GetString("TmCharityBoxesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box List.
        /// </summary>
        public static string TmCharityBoxList {
            get {
                return ResourceManager.GetString("TmCharityBoxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity Box Receive.
        /// </summary>
        public static string TmCharityBoxReceive {
            get {
                return ResourceManager.GetString("TmCharityBoxReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged Charity Boxs.
        /// </summary>
        public static string TmDamagedCharityBoxs {
            get {
                return ResourceManager.GetString("TmDamagedCharityBoxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string TmLocations {
            get {
                return ResourceManager.GetString("TmLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string TmRegions {
            get {
                return ResourceManager.GetString("TmRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisors.
        /// </summary>
        public static string TmSupervisors {
            get {
                return ResourceManager.GetString("TmSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Booking.
        /// </summary>
        public static string UnitsBooking {
            get {
                return ResourceManager.GetString("UnitsBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Conversion.
        /// </summary>
        public static string UnitsConversion {
            get {
                return ResourceManager.GetString("UnitsConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string User_Management {
            get {
                return ResourceManager.GetString("User_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variations.
        /// </summary>
        public static string Variations {
            get {
                return ResourceManager.GetString("Variations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Account Statement.
        /// </summary>
        public static string VendorAccountStatement {
            get {
                return ResourceManager.GetString("VendorAccountStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting List.
        /// </summary>
        public static string WaitingList {
            get {
                return ResourceManager.GetString("WaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebViews.
        /// </summary>
        public static string WebViews {
            get {
                return ResourceManager.GetString("WebViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Views Docs.
        /// </summary>
        public static string WebViewsDocs {
            get {
                return ResourceManager.GetString("WebViewsDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string WorkStructure {
            get {
                return ResourceManager.GetString("WorkStructure", resourceCulture);
            }
        }
    }
}
