//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.SpGuarantees {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpCaseOperations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpCaseOperations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.SpGuarantees.SpCaseOperations", typeof(SpCaseOperations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficent Name.
        /// </summary>
        public static string BeneficentName {
            get {
                return ResourceManager.GetString("BeneficentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficent Number.
        /// </summary>
        public static string BeneficentNumber {
            get {
                return ResourceManager.GetString("BeneficentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Case.
        /// </summary>
        public static string BtnCancelCase {
            get {
                return ResourceManager.GetString("BtnCancelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string BtnReplaceCase {
            get {
                return ResourceManager.GetString("BtnReplaceCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off Case.
        /// </summary>
        public static string BtnTurnOffCase {
            get {
                return ResourceManager.GetString("BtnTurnOffCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Date.
        /// </summary>
        public static string CaseDate {
            get {
                return ResourceManager.GetString("CaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Name.
        /// </summary>
        public static string CaseName {
            get {
                return ResourceManager.GetString("CaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Number.
        /// </summary>
        public static string CaseNumber {
            get {
                return ResourceManager.GetString("CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Check At Least One Case.
        /// </summary>
        public static string MustCheckAtLeastOneCase {
            get {
                return ResourceManager.GetString("MustCheckAtLeastOneCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Choose Case Or Beneficent.
        /// </summary>
        public static string MustChooseCaseOrBenf {
            get {
                return ResourceManager.GetString("MustChooseCaseOrBenf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Case.
        /// </summary>
        public static string NewCaseId {
            get {
                return ResourceManager.GetString("NewCaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Case Number.
        /// </summary>
        public static string NewCaseNumber {
            get {
                return ResourceManager.GetString("NewCaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Date.
        /// </summary>
        public static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Type.
        /// </summary>
        public static string OperationTypeLkpId {
            get {
                return ResourceManager.GetString("OperationTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string ReasonLkpId {
            get {
                return ResourceManager.GetString("ReasonLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Operation.
        /// </summary>
        public static string ReplaceOperation {
            get {
                return ResourceManager.GetString("ReplaceOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpContractDetailsId.
        /// </summary>
        public static string SpContractDetailsId {
            get {
                return ResourceManager.GetString("SpContractDetailsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Name.
        /// </summary>
        public static string SponsorLkpNameAr {
            get {
                return ResourceManager.GetString("SponsorLkpNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases Operations.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
