//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.SpGuarantees {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpFamilies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpFamilies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.SpGuarantees.SpFamilies", typeof(SpFamilies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Owner.
        /// </summary>
        public static string AccountOwner {
            get {
                return ResourceManager.GetString("AccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string BankLkpId {
            get {
                return ResourceManager.GetString("BankLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Name.
        /// </summary>
        public static string CaseName {
            get {
                return ResourceManager.GetString("CaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityLkpId {
            get {
                return ResourceManager.GetString("CityLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duties.
        /// </summary>
        public static string Duties {
            get {
                return ResourceManager.GetString("Duties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Description.
        /// </summary>
        public static string DutyDescription {
            get {
                return ResourceManager.GetString("DutyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Type.
        /// </summary>
        public static string DutyType {
            get {
                return ResourceManager.GetString("DutyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Number.
        /// </summary>
        public static string FamilyNumber {
            get {
                return ResourceManager.GetString("FamilyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Died Date.
        /// </summary>
        public static string FatherDiedDate {
            get {
                return ResourceManager.GetString("FatherDiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Died Reason.
        /// </summary>
        public static string FatherDiedReason {
            get {
                return ResourceManager.GetString("FatherDiedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Name.
        /// </summary>
        public static string GuardianName {
            get {
                return ResourceManager.GetString("GuardianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing Status.
        /// </summary>
        public static string HousingStatusLkpId {
            get {
                return ResourceManager.GetString("HousingStatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing Type.
        /// </summary>
        public static string HousingTypeLkpId {
            get {
                return ResourceManager.GetString("HousingTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Expiration Date.
        /// </summary>
        public static string IdExpirationDate {
            get {
                return ResourceManager.GetString("IdExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomes.
        /// </summary>
        public static string Incomes {
            get {
                return ResourceManager.GetString("Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Source.
        /// </summary>
        public static string IncomeSource {
            get {
                return ResourceManager.GetString("IncomeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Source Name.
        /// </summary>
        public static string IncomeSourceName {
            get {
                return ResourceManager.GetString("IncomeSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFatherDied.
        /// </summary>
        public static string IsFatherDied {
            get {
                return ResourceManager.GetString("IsFatherDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsHasHouse.
        /// </summary>
        public static string IsHasHouse {
            get {
                return ResourceManager.GetString("IsHasHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMotherDied.
        /// </summary>
        public static string IsMotherDied {
            get {
                return ResourceManager.GetString("IsMotherDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatusLkpId {
            get {
                return ResourceManager.GetString("MaritalStatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number1.
        /// </summary>
        public static string MobileNumber1 {
            get {
                return ResourceManager.GetString("MobileNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number2.
        /// </summary>
        public static string MobileNumber2 {
            get {
                return ResourceManager.GetString("MobileNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Amount.
        /// </summary>
        public static string MonthlyAmount {
            get {
                return ResourceManager.GetString("MonthlyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Income Amount.
        /// </summary>
        public static string MonthlyIncomeAmount {
            get {
                return ResourceManager.GetString("MonthlyIncomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Outcome Amount.
        /// </summary>
        public static string MonthlyOutcomeAmount {
            get {
                return ResourceManager.GetString("MonthlyOutcomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Died Date.
        /// </summary>
        public static string MotherDiedDate {
            get {
                return ResourceManager.GetString("MotherDiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Died Reason.
        /// </summary>
        public static string MotherDiedReason {
            get {
                return ResourceManager.GetString("MotherDiedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string NationalityLkpId {
            get {
                return ResourceManager.GetString("NationalityLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Of Birth.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatives Type.
        /// </summary>
        public static string RelativesTypeLkpId {
            get {
                return ResourceManager.GetString("RelativesTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Category.
        /// </summary>
        public static string SponsorCategoryLkpId {
            get {
                return ResourceManager.GetString("SponsorCategoryLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalDuties.
        /// </summary>
        public static string TotalDuties {
            get {
                return ResourceManager.GetString("TotalDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalIncomes.
        /// </summary>
        public static string TotalIncomes {
            get {
                return ResourceManager.GetString("TotalIncomes", resourceCulture);
            }
        }
    }
}
