//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.PmPropertiesModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FmContracts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FmContracts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.PmPropertiesModule.FmContracts", typeof(FmContracts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Value.
        /// </summary>
        public static string Accountvalue {
            get {
                return ResourceManager.GetString("Accountvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adv Account.
        /// </summary>
        public static string AdvAccountId {
            get {
                return ResourceManager.GetString("AdvAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adv Account .
        /// </summary>
        public static string AdvAccountValue {
            get {
                return ResourceManager.GetString("AdvAccountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Amount.
        /// </summary>
        public static string AnnualAmount {
            get {
                return ResourceManager.GetString("AnnualAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string EngineerId {
            get {
                return ResourceManager.GetString("EngineerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Details .
        /// </summary>
        public static string FillDetailTable {
            get {
                return ResourceManager.GetString("FillDetailTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FmBuildingsContracts.
        /// </summary>
        public static string FmBuildingsContracts {
            get {
                return ResourceManager.GetString("FmBuildingsContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FmContractVisits.
        /// </summary>
        public static string FmContractVisits {
            get {
                return ResourceManager.GetString("FmContractVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type .
        /// </summary>
        public static string PaymentTypeLkpId {
            get {
                return ResourceManager.GetString("PaymentTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment .
        /// </summary>
        public static string PaymentTypeLkpValue {
            get {
                return ResourceManager.GetString("PaymentTypeLkpValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string PmPropertiesId {
            get {
                return ResourceManager.GetString("PmPropertiesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Amount Must Equal annual Amount.
        /// </summary>
        public static string RentalAmountValidation {
            get {
                return ResourceManager.GetString("RentalAmountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Amount.
        /// </summary>
        public static string RentAmount {
            get {
                return ResourceManager.GetString("RentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rowStatus.
        /// </summary>
        public static string rowStatus {
            get {
                return ResourceManager.GetString("rowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLkpId {
            get {
                return ResourceManager.GetString("StatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLkpValue {
            get {
                return ResourceManager.GetString("StatusLkpValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FmContracts.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Contract Number.
        /// </summary>
        public static string VendorContractNumber {
            get {
                return ResourceManager.GetString("VendorContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Value.
        /// </summary>
        public static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Value.
        /// </summary>
        public static string VendorValue {
            get {
                return ResourceManager.GetString("VendorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        public static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Number.
        /// </summary>
        public static string VisitNumber {
            get {
                return ResourceManager.GetString("VisitNumber", resourceCulture);
            }
        }
    }
}
