//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.PmPropertiesModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PmTenants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PmTenants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.PmPropertiesModule.PmTenants", typeof(PmTenants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityLkpId {
            get {
                return ResourceManager.GetString("CityLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial License Expiry Date.
        /// </summary>
        public static string CommercialLicenseExpiryDate {
            get {
                return ResourceManager.GetString("CommercialLicenseExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial License Number.
        /// </summary>
        public static string CommercialLicenseNumber {
            get {
                return ResourceManager.GetString("CommercialLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryLkpId {
            get {
                return ResourceManager.GetString("CountryLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Data.
        /// </summary>
        public static string DetailData {
            get {
                return ResourceManager.GetString("DetailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Detail Table.
        /// </summary>
        public static string FillDetailTable {
            get {
                return ResourceManager.GetString("FillDetailTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string HomePhoneNumber {
            get {
                return ResourceManager.GetString("HomePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Expiration Date.
        /// </summary>
        public static string IdExpirationDate {
            get {
                return ResourceManager.GetString("IdExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length 15.
        /// </summary>
        public static string IdMaxLength {
            get {
                return ResourceManager.GetString("IdMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Length 15.
        /// </summary>
        public static string IdMinLength {
            get {
                return ResourceManager.GetString("IdMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Numbers Repeated !!.
        /// </summary>
        public static string IdNumbersRepeated {
            get {
                return ResourceManager.GetString("IdNumbersRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number Registerd Before.
        /// </summary>
        public static string IdRegisterdBefore {
            get {
                return ResourceManager.GetString("IdRegisterdBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatusLkpId {
            get {
                return ResourceManager.GetString("MaritalStatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string NationalityLkpId {
            get {
                return ResourceManager.GetString("NationalityLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Address.
        /// </summary>
        public static string OtherAddress {
            get {
                return ResourceManager.GetString("OtherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Country.
        /// </summary>
        public static string PassportCountryLkpId {
            get {
                return ResourceManager.GetString("PassportCountryLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiry Date.
        /// </summary>
        public static string PassportExpiryDate {
            get {
                return ResourceManager.GetString("PassportExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Issue Date.
        /// </summary>
        public static string PassportIssueDate {
            get {
                return ResourceManager.GetString("PassportIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethodLkpId {
            get {
                return ResourceManager.GetString("PaymentMethodLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoBox.
        /// </summary>
        public static string PoBox {
            get {
                return ResourceManager.GetString("PoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence End Date.
        /// </summary>
        public static string ResidenceEndDate {
            get {
                return ResourceManager.GetString("ResidenceEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string SpecialGenderLkpId {
            get {
                return ResourceManager.GetString("SpecialGenderLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLkpId {
            get {
                return ResourceManager.GetString("StatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string TenantName {
            get {
                return ResourceManager.GetString("TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name Arabic.
        /// </summary>
        public static string TenantNameAr {
            get {
                return ResourceManager.GetString("TenantNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name English.
        /// </summary>
        public static string TenantNameEn {
            get {
                return ResourceManager.GetString("TenantNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Number.
        /// </summary>
        public static string TenantNumber {
            get {
                return ResourceManager.GetString("TenantNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone Number.
        /// </summary>
        public static string WorkPhoneNumber {
            get {
                return ResourceManager.GetString("WorkPhoneNumber", resourceCulture);
            }
        }
    }
}
