//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.Accounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApMiscPaymentHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApMiscPaymentHeaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.Accounts.ApMiscPaymentHeaders", typeof(ApMiscPaymentHeaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Tax.
        /// </summary>
        public static string AccountTax {
            get {
                return ResourceManager.GetString("AccountTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc Payee Only.
        /// </summary>
        public static string AccPayeeOnly {
            get {
                return ResourceManager.GetString("AccPayeeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminitrative Ammount.
        /// </summary>
        public static string AdminitrativeAmmount {
            get {
                return ResourceManager.GetString("AdminitrativeAmmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminitrative Percent %.
        /// </summary>
        public static string AdminitrativePercent {
            get {
                return ResourceManager.GetString("AdminitrativePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Not Valid.
        /// </summary>
        public static string AmountNotValid {
            get {
                return ResourceManager.GetString("AmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string BankAccountId {
            get {
                return ResourceManager.GetString("BankAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Banks/Boxes.
        /// </summary>
        public static string BankBoxes {
            get {
                return ResourceManager.GetString("BankBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Name.
        /// </summary>
        public static string BeneficiaryName {
            get {
                return ResourceManager.GetString("BeneficiaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Amount Not Valid.
        /// </summary>
        public static string CheckAmountNotValid {
            get {
                return ResourceManager.GetString("CheckAmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Number.
        /// </summary>
        public static string CheckNumber {
            get {
                return ResourceManager.GetString("CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        public static string CollectorId {
            get {
                return ResourceManager.GetString("CollectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Detail Data.
        /// </summary>
        public static string DetailData {
            get {
                return ResourceManager.GetString("DetailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill detail table.
        /// </summary>
        public static string FillDetailTable {
            get {
                return ResourceManager.GetString("FillDetailTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form detail not valid.
        /// </summary>
        public static string FormDetailNotValid {
            get {
                return ResourceManager.GetString("FormDetailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active ?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Receipt Number.
        /// </summary>
        public static string ManualReceiptNumber {
            get {
                return ResourceManager.GetString("ManualReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Receipt Number Lines.
        /// </summary>
        public static string ManualReceiptNumberLines {
            get {
                return ResourceManager.GetString("ManualReceiptNumberLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        public static string MasterData {
            get {
                return ResourceManager.GetString("MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity Date.
        /// </summary>
        public static string MaturityDate {
            get {
                return ResourceManager.GetString("MaturityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Payment Amount.
        /// </summary>
        public static string MiscPaymentAmount {
            get {
                return ResourceManager.GetString("MiscPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Payment Date.
        /// </summary>
        public static string MiscPaymentDate {
            get {
                return ResourceManager.GetString("MiscPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Receipt Date.
        /// </summary>
        public static string MiscReceiptDate {
            get {
                return ResourceManager.GetString("MiscReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Receipt.
        /// </summary>
        public static string MiscReceiptId {
            get {
                return ResourceManager.GetString("MiscReceiptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therefor about.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Number.
        /// </summary>
        public static string PaymentNumber {
            get {
                return ResourceManager.GetString("PaymentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentTypeLkpId {
            get {
                return ResourceManager.GetString("PaymentTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal User.
        /// </summary>
        public static string PortalUsersId {
            get {
                return ResourceManager.GetString("PortalUsersId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PostedLkpId {
            get {
                return ResourceManager.GetString("PostedLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Type.
        /// </summary>
        public static string ReceiptTypeLkpId {
            get {
                return ResourceManager.GetString("ReceiptTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCodeLkpId {
            get {
                return ResourceManager.GetString("SourceCodeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax No.
        /// </summary>
        public static string TaxNo {
            get {
                return ResourceManager.GetString("TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Percent.
        /// </summary>
        public static string TaxPercent {
            get {
                return ResourceManager.GetString("TaxPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Voucher.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ap Misc Payment Lines.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ap Misc Payment Details.
        /// </summary>
        public static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrTax.
        /// </summary>
        public static string TrTax {
            get {
                return ResourceManager.GetString("TrTax", resourceCulture);
            }
        }
    }
}
