//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.Accounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArMiscReceiptHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArMiscReceiptHeaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.Accounts.ArMiscReceiptHeaders", typeof(ArMiscReceiptHeaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SpBeneficent.
        /// </summary>
        public static string AddSpBeneficent {
            get {
                return ResourceManager.GetString("AddSpBeneficent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Account.
        /// </summary>
        public static string AdminAccount {
            get {
                return ResourceManager.GetString("AdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminitrative Ammount.
        /// </summary>
        public static string AdminitrativeAmmount {
            get {
                return ResourceManager.GetString("AdminitrativeAmmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminitrative Percent %.
        /// </summary>
        public static string AdminitrativePercent {
            get {
                return ResourceManager.GetString("AdminitrativePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Not Valid.
        /// </summary>
        public static string AmountNotValid {
            get {
                return ResourceManager.GetString("AmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string BankAccountId {
            get {
                return ResourceManager.GetString("BankAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string BankLkp {
            get {
                return ResourceManager.GetString("BankLkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficent.
        /// </summary>
        public static string BeneficentId {
            get {
                return ResourceManager.GetString("BeneficentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box/Banks.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Amount.
        /// </summary>
        public static string CheckAmount {
            get {
                return ResourceManager.GetString("CheckAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Amount Not Valid.
        /// </summary>
        public static string CheckAmountNotValid {
            get {
                return ResourceManager.GetString("CheckAmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Number.
        /// </summary>
        public static string CheckNumber {
            get {
                return ResourceManager.GetString("CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        public static string CollectorId {
            get {
                return ResourceManager.GetString("CollectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Banks.
        /// </summary>
        public static string DepositBanks {
            get {
                return ResourceManager.GetString("DepositBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Detail Data.
        /// </summary>
        public static string DetailData {
            get {
                return ResourceManager.GetString("DetailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details More Than Two Not Valid.
        /// </summary>
        public static string DetailsMoreThanTwo {
            get {
                return ResourceManager.GetString("DetailsMoreThanTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill detail table.
        /// </summary>
        public static string FillDetailTable {
            get {
                return ResourceManager.GetString("FillDetailTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form detail not valid.
        /// </summary>
        public static string FormDetailNotValid {
            get {
                return ResourceManager.GetString("FormDetailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active ?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Receipt Number.
        /// </summary>
        public static string ManualReceiptNumber {
            get {
                return ResourceManager.GetString("ManualReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Receipt Number Lines.
        /// </summary>
        public static string ManualReceiptNumberLines {
            get {
                return ResourceManager.GetString("ManualReceiptNumberLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        public static string MasterData {
            get {
                return ResourceManager.GetString("MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity Date.
        /// </summary>
        public static string MaturityDate {
            get {
                return ResourceManager.GetString("MaturityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Receipt Date.
        /// </summary>
        public static string MiscReceiptDate {
            get {
                return ResourceManager.GetString("MiscReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Receipt Details Required.
        /// </summary>
        public static string MiscReceiptDetailsRequired {
            get {
                return ResourceManager.GetString("MiscReceiptDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Receipt.
        /// </summary>
        public static string MiscReceiptId {
            get {
                return ResourceManager.GetString("MiscReceiptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PostedLkpId {
            get {
                return ResourceManager.GetString("PostedLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Number.
        /// </summary>
        public static string ReceiptNumber {
            get {
                return ResourceManager.GetString("ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Type.
        /// </summary>
        public static string ReceiptType {
            get {
                return ResourceManager.GetString("ReceiptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Type.
        /// </summary>
        public static string ReceiptTypeLkpId {
            get {
                return ResourceManager.GetString("ReceiptTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCodeLkpId {
            get {
                return ResourceManager.GetString("SourceCodeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar Misc Receipt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar Misc Receipt Lines.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar Misc Receipt Details.
        /// </summary>
        public static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TransactionTypeLkpId {
            get {
                return ResourceManager.GetString("TransactionTypeLkpId", resourceCulture);
            }
        }
    }
}
