//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.Accounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportsAccounts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportsAccounts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.Accounts.ReportsAccounts", typeof(ReportsAccounts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Tree.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Statment.
        /// </summary>
        public static string AccountStatment {
            get {
                return ResourceManager.GetString("AccountStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Days.
        /// </summary>
        public static string AddDays {
            get {
                return ResourceManager.GetString("AddDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Value.
        /// </summary>
        public static string AdminValue {
            get {
                return ResourceManager.GetString("AdminValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApPdcInterface Report.
        /// </summary>
        public static string ApPdcInterface {
            get {
                return ResourceManager.GetString("ApPdcInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ap Pdc Interface Report.
        /// </summary>
        public static string ApPdcInterfaceReportTitle {
            get {
                return ResourceManager.GetString("ApPdcInterfaceReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArPdcInterface Report.
        /// </summary>
        public static string ArPdcInterface {
            get {
                return ResourceManager.GetString("ArPdcInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar Pdc Interface Report.
        /// </summary>
        public static string ArPdcInterfaceReportTitle {
            get {
                return ResourceManager.GetString("ArPdcInterfaceReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail Balance.
        /// </summary>
        public static string BalanceReview {
            get {
                return ResourceManager.GetString("BalanceReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        public static string BaseCurrency {
            get {
                return ResourceManager.GetString("BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box No.
        /// </summary>
        public static string BoxNo {
            get {
                return ResourceManager.GetString("BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Performance.
        /// </summary>
        public static string BudgetPerformance {
            get {
                return ResourceManager.GetString("BudgetPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contract End.
        /// </summary>
        public static string contractEndDate {
            get {
                return ResourceManager.GetString("contractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start.
        /// </summary>
        public static string ContractStartDate {
            get {
                return ResourceManager.GetString("ContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreationTime.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Proccessed Successfully.
        /// </summary>
        public static string DataProccessedSuccessfully {
            get {
                return ResourceManager.GetString("DataProccessedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Processing.
        /// </summary>
        public static string DataProcessing {
            get {
                return ResourceManager.GetString("DataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter All Data.
        /// </summary>
        public static string EnterData {
            get {
                return ResourceManager.GetString("EnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execlude Paid Invoices.
        /// </summary>
        public static string ExecutedInvoices {
            get {
                return ResourceManager.GetString("ExecutedInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaAssets List.
        /// </summary>
        public static string FaAssetList {
            get {
                return ResourceManager.GetString("FaAssetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Faild {
            get {
                return ResourceManager.GetString("Faild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Buying Date.
        /// </summary>
        public static string FromBuyingDate {
            get {
                return ResourceManager.GetString("FromBuyingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Period.
        /// </summary>
        public static string FromPeriod {
            get {
                return ResourceManager.GetString("FromPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string GlAccMappingHd {
            get {
                return ResourceManager.GetString("GlAccMappingHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Statement.
        /// </summary>
        public static string GlAccSelection {
            get {
                return ResourceManager.GetString("GlAccSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Checks.
        /// </summary>
        public static string IssuedChecks {
            get {
                return ResourceManager.GetString("IssuedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit and Loss.
        /// </summary>
        public static string ListIncomes {
            get {
                return ResourceManager.GetString("ListIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        public static string ManagerName {
            get {
                return ResourceManager.GetString("ManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerId {
            get {
                return ResourceManager.GetString("OwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Number.
        /// </summary>
        public static string OwnerNumber {
            get {
                return ResourceManager.GetString("OwnerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string PmActivityId {
            get {
                return ResourceManager.GetString("PmActivityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-renewed contract disclosure report.
        /// </summary>
        public static string PmContractNotRenewed {
            get {
                return ResourceManager.GetString("PmContractNotRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts List Report.
        /// </summary>
        public static string pmContracts {
            get {
                return ResourceManager.GetString("pmContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacant units report.
        /// </summary>
        public static string PmsList {
            get {
                return ResourceManager.GetString("PmsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string PMTenantId {
            get {
                return ResourceManager.GetString("PMTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        public static string PmUnitTypeLkpId {
            get {
                return ResourceManager.GetString("PmUnitTypeLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proccessing Data Required.
        /// </summary>
        public static string ProcessingDataRequired {
            get {
                return ResourceManager.GetString("ProcessingDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string PropertiesRevenue {
            get {
                return ResourceManager.GetString("PropertiesRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        public static string PropertyId {
            get {
                return ResourceManager.GetString("PropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Number.
        /// </summary>
        public static string propertyNumber {
            get {
                return ResourceManager.GetString("propertyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Days.
        /// </summary>
        public static string RemainingDays {
            get {
                return ResourceManager.GetString("RemainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Date.
        /// </summary>
        public static string RenewalDate {
            get {
                return ResourceManager.GetString("RenewalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Representative Name.
        /// </summary>
        public static string RepManagerName {
            get {
                return ResourceManager.GetString("RepManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Per Nationality.
        /// </summary>
        public static string RequestPerNationality {
            get {
                return ResourceManager.GetString("RequestPerNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_GL_JE.
        /// </summary>
        public static string RPT_Get_GL_JE_EnTitle {
            get {
                return ResourceManager.GetString("RPT_Get_GL_JE_EnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit and Loss.
        /// </summary>
        public static string RPT_GetGeneralBalanceSheetTitle {
            get {
                return ResourceManager.GetString("RPT_GetGeneralBalanceSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        public static string RPT_GetGeneralBalanceSheetTitlee {
            get {
                return ResourceManager.GetString("RPT_GetGeneralBalanceSheetTitlee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balances.
        /// </summary>
        public static string RPT_GetgltrialbalancesTitle {
            get {
                return ResourceManager.GetString("RPT_GetgltrialbalancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Tree.
        /// </summary>
        public static string rptAccountsTreeTitle {
            get {
                return ResourceManager.GetString("rptAccountsTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Invoices.
        /// </summary>
        public static string rptArInvoiceHdScreenTitle {
            get {
                return ResourceManager.GetString("rptArInvoiceHdScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset List.
        /// </summary>
        public static string rptFaAssetListTitle {
            get {
                return ResourceManager.GetString("rptFaAssetListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string rptGlAccountsScreenTitle {
            get {
                return ResourceManager.GetString("rptGlAccountsScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Details.
        /// </summary>
        public static string rptGlJeScreenTitle {
            get {
                return ResourceManager.GetString("rptGlJeScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers Invoice.
        /// </summary>
        public static string rptInvoiceHdScreenTitle {
            get {
                return ResourceManager.GetString("rptInvoiceHdScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Report.
        /// </summary>
        public static string rptIvReceiveHdScreenTitle {
            get {
                return ResourceManager.GetString("rptIvReceiveHdScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Spending Issue.
        /// </summary>
        public static string rptIvStoreIssueHdScreenTitle {
            get {
                return ResourceManager.GetString("rptIvStoreIssueHdScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Report.
        /// </summary>
        public static string rptPoPurchaseOrderScreenTitle {
            get {
                return ResourceManager.GetString("rptPoPurchaseOrderScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Details.
        /// </summary>
        public static string rptSecurityDetailsListTitle {
            get {
                return ResourceManager.GetString("rptSecurityDetailsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLKkpId {
            get {
                return ResourceManager.GetString("StatusLKkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot renew users subscriptions for a period longer than the administrator subscription.
        /// </summary>
        public static string SubEndDateValidation {
            get {
                return ResourceManager.GetString("SubEndDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Saved.
        /// </summary>
        public static string Sved {
            get {
                return ResourceManager.GetString("Sved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Input.
        /// </summary>
        public static string TaxInput {
            get {
                return ResourceManager.GetString("TaxInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Output.
        /// </summary>
        public static string TaxOutput {
            get {
                return ResourceManager.GetString("TaxOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registration (15).
        /// </summary>
        public static string TaxRegNo {
            get {
                return ResourceManager.GetString("TaxRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Registration.
        /// </summary>
        public static string TaxRegNum {
            get {
                return ResourceManager.GetString("TaxRegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Taxs.
        /// </summary>
        public static string TaxReports {
            get {
                return ResourceManager.GetString("TaxReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Taxs.
        /// </summary>
        public static string TaxReports2 {
            get {
                return ResourceManager.GetString("TaxReports2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taxsReports.
        /// </summary>
        public static string taxsReports {
            get {
                return ResourceManager.GetString("taxsReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taxsReports2.
        /// </summary>
        public static string taxsReports2 {
            get {
                return ResourceManager.GetString("taxsReports2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Customer Account Statement.
        /// </summary>
        public static string TenantAccount {
            get {
                return ResourceManager.GetString("TenantAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string TenantName {
            get {
                return ResourceManager.GetString("TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string TenantNameAr {
            get {
                return ResourceManager.GetString("TenantNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name En.
        /// </summary>
        public static string TenantNameEn {
            get {
                return ResourceManager.GetString("TenantNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number.
        /// </summary>
        public static string TenantNumber {
            get {
                return ResourceManager.GetString("TenantNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TenantData.
        /// </summary>
        public static string TitleTenant {
            get {
                return ResourceManager.GetString("TitleTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Buying Date.
        /// </summary>
        public static string ToBuyingDate {
            get {
                return ResourceManager.GetString("ToBuyingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Period.
        /// </summary>
        public static string ToPeriod {
            get {
                return ResourceManager.GetString("ToPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Value.
        /// </summary>
        public static string UserValue {
            get {
                return ResourceManager.GetString("UserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
