//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.AccountsExtend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlAccMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlAccMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.AccountsExtend.GlAccMapping", typeof(GlAccMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account DescriptionAr.
        /// </summary>
        public static string FromAccDescriptionAr {
            get {
                return ResourceManager.GetString("FromAccDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account DescriptionEn.
        /// </summary>
        public static string FromAccDescriptionEn {
            get {
                return ResourceManager.GetString("FromAccDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        public static string FromAccId {
            get {
                return ResourceManager.GetString("FromAccId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlAcc MappingTr.
        /// </summary>
        public static string GlAccMappingTr {
            get {
                return ResourceManager.GetString("GlAccMappingTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlAcc MappingTrDtl.
        /// </summary>
        public static string GlAccMappingTrDtl {
            get {
                return ResourceManager.GetString("GlAccMappingTrDtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Name.
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Number.
        /// </summary>
        public static string MapNumber {
            get {
                return ResourceManager.GetString("MapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlAcc Mapping.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account DescriptionAr.
        /// </summary>
        public static string ToAccDescriptionAr {
            get {
                return ResourceManager.GetString("ToAccDescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account DescriptionEn.
        /// </summary>
        public static string ToAccDescriptionEn {
            get {
                return ResourceManager.GetString("ToAccDescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        public static string ToAccId {
            get {
                return ResourceManager.GetString("ToAccId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tr Name.
        /// </summary>
        public static string TrName {
            get {
                return ResourceManager.GetString("TrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tr No.
        /// </summary>
        public static string TrNo {
            get {
                return ResourceManager.GetString("TrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeLkpId {
            get {
                return ResourceManager.GetString("TypeLkpId", resourceCulture);
            }
        }
    }
}
