//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.AccountsExtend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlJeIntegrationHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlJeIntegrationHeaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.AccountsExtend.GlJeIntegrationHeaders", typeof(GlJeIntegrationHeaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Lines.
        /// </summary>
        public static string AccountLines {
            get {
                return ResourceManager.GetString("AccountLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string ApVendorId {
            get {
                return ResourceManager.GetString("ApVendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string ArCustomerId {
            get {
                return ResourceManager.GetString("ArCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount.
        /// </summary>
        public static string CreditAmount {
            get {
                return ResourceManager.GetString("CreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyId {
            get {
                return ResourceManager.GetString("CurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        public static string CurrencyRate {
            get {
                return ResourceManager.GetString("CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Lines.
        /// </summary>
        public static string CustomerLines {
            get {
                return ResourceManager.GetString("CustomerLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number.
        /// </summary>
        public static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Amount.
        /// </summary>
        public static string DebitAmount {
            get {
                return ResourceManager.GetString("DebitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Journal Entry Date.
        /// </summary>
        public static string GlJeIntegrationDate {
            get {
                return ResourceManager.GetString("GlJeIntegrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string GlJeIntegrationNotes {
            get {
                return ResourceManager.GetString("GlJeIntegrationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Journal Entry No.
        /// </summary>
        public static string GlJeIntegrationNumber {
            get {
                return ResourceManager.GetString("GlJeIntegrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlJeIntegration Source.
        /// </summary>
        public static string GlJeIntegrationSourceId {
            get {
                return ResourceManager.GetString("GlJeIntegrationSourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Journal Entry Source.
        /// </summary>
        public static string GlJeIntegrationSourceLkpId {
            get {
                return ResourceManager.GetString("GlJeIntegrationSourceLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source No.
        /// </summary>
        public static string GlJeIntegrationSourceNo {
            get {
                return ResourceManager.GetString("GlJeIntegrationSourceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JeName.
        /// </summary>
        public static string JeName {
            get {
                return ResourceManager.GetString("JeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string PeriodId {
            get {
                return ResourceManager.GetString("PeriodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status .
        /// </summary>
        public static string StatusLkpId {
            get {
                return ResourceManager.GetString("StatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Journal Entries.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Lines.
        /// </summary>
        public static string VendorLines {
            get {
                return ResourceManager.GetString("VendorLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Number.
        /// </summary>
        public static string VendorNumber {
            get {
                return ResourceManager.GetString("VendorNumber", resourceCulture);
            }
        }
    }
}
