//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.AidModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScMaintenanceContract {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScMaintenanceContract() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.AidModule.ScMaintenanceContract", typeof(ScMaintenanceContract).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Data.
        /// </summary>
        public static string ContractData {
            get {
                return ResourceManager.GetString("ContractData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Terms.
        /// </summary>
        public static string ContractTerms {
            get {
                return ResourceManager.GetString("ContractTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Of Implementation.
        /// </summary>
        public static string DurationOfImplementation {
            get {
                return ResourceManager.GetString("DurationOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Contract Date.
        /// </summary>
        public static string MaintenanceContractDate {
            get {
                return ResourceManager.GetString("MaintenanceContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Contract Number.
        /// </summary>
        public static string MaintenanceContractNumber {
            get {
                return ResourceManager.GetString("MaintenanceContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Contract Payments.
        /// </summary>
        public static string MaintenanceContractPayments {
            get {
                return ResourceManager.GetString("MaintenanceContractPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Contract Terms.
        /// </summary>
        public static string OtherContractTerms {
            get {
                return ResourceManager.GetString("OtherContractTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payemt No.
        /// </summary>
        public static string PayemtNo {
            get {
                return ResourceManager.GetString("PayemtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Condition.
        /// </summary>
        public static string PaymentCondition {
            get {
                return ResourceManager.GetString("PaymentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Request Number.
        /// </summary>
        public static string PortalRequestNumber {
            get {
                return ResourceManager.GetString("PortalRequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal User Name.
        /// </summary>
        public static string PortalUserName {
            get {
                return ResourceManager.GetString("PortalUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Quotation.
        /// </summary>
        public static string ScMaintenanceQuotationId {
            get {
                return ResourceManager.GetString("ScMaintenanceQuotationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLkpId {
            get {
                return ResourceManager.GetString("StatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Contracts.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
    }
}
