//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.AidModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScPortalRequestStudy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScPortalRequestStudy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.AidModule.ScPortalRequestStudy", typeof(ScPortalRequestStudy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Name.
        /// </summary>
        public static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Name.
        /// </summary>
        public static string CaseName {
            get {
                return ResourceManager.GetString("CaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashing To.
        /// </summary>
        public static string CashingTo {
            get {
                return ResourceManager.GetString("CashingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Manager/Committee.
        /// </summary>
        public static string DecisionInfo {
            get {
                return ResourceManager.GetString("DecisionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Data.
        /// </summary>
        public static string DetailData {
            get {
                return ResourceManager.GetString("DetailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse Resaon For Edit.
        /// </summary>
        public static string ManagerRefuseResaon {
            get {
                return ResourceManager.GetString("ManagerRefuseResaon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Months.
        /// </summary>
        public static string NoOfMonths {
            get {
                return ResourceManager.GetString("NoOfMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Attachment.
        /// </summary>
        public static string PleaseUploadAttachment {
            get {
                return ResourceManager.GetString("PleaseUploadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Number.
        /// </summary>
        public static string PortalRequestId {
            get {
                return ResourceManager.GetString("PortalRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse Description.
        /// </summary>
        public static string RefuseDescription {
            get {
                return ResourceManager.GetString("RefuseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        public static string RefuseLkpId {
            get {
                return ResourceManager.GetString("RefuseLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher Decision.
        /// </summary>
        public static string ResearcherDecision {
            get {
                return ResourceManager.GetString("ResearcherDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher Name.
        /// </summary>
        public static string ResearcherName {
            get {
                return ResourceManager.GetString("ResearcherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status .
        /// </summary>
        public static string StatusLkpId {
            get {
                return ResourceManager.GetString("StatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Date.
        /// </summary>
        public static string StudyDate {
            get {
                return ResourceManager.GetString("StudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Details.
        /// </summary>
        public static string StudyDetails {
            get {
                return ResourceManager.GetString("StudyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Kind.
        /// </summary>
        public static string StudyLkpId {
            get {
                return ResourceManager.GetString("StudyLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Number.
        /// </summary>
        public static string StudyNumber {
            get {
                return ResourceManager.GetString("StudyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Amount.
        /// </summary>
        public static string SuggestedAmount {
            get {
                return ResourceManager.GetString("SuggestedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Requests.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
