//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.ResourcePack.HR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PyPayrollOperations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PyPayrollOperations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.ResourcePack.HR.PyPayrollOperations", typeof(PyPayrollOperations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string BankLkpId {
            get {
                return ResourceManager.GetString("BankLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Amount.
        /// </summary>
        public static string DeductionAmount {
            get {
                return ResourceManager.GetString("DeductionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning Amount.
        /// </summary>
        public static string EarningAmount {
            get {
                return ResourceManager.GetString("EarningAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HrPerson.
        /// </summary>
        public static string HrPersonId {
            get {
                return ResourceManager.GetString("HrPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HrPerson Number.
        /// </summary>
        public static string HrPersonNumber {
            get {
                return ResourceManager.GetString("HrPersonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string JobLkpId {
            get {
                return ResourceManager.GetString("JobLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Date.
        /// </summary>
        public static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Number.
        /// </summary>
        public static string OperationNumber {
            get {
                return ResourceManager.GetString("OperationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayRoll Details.
        /// </summary>
        public static string PayRollDetails {
            get {
                return ResourceManager.GetString("PayRollDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Net Value.
        /// </summary>
        public static string PayrollNetValue {
            get {
                return ResourceManager.GetString("PayrollNetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayRoll Persons.
        /// </summary>
        public static string PayRollPersons {
            get {
                return ResourceManager.GetString("PayRollPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Total Value.
        /// </summary>
        public static string PayrollTotalValue {
            get {
                return ResourceManager.GetString("PayrollTotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string PeriodId {
            get {
                return ResourceManager.GetString("PeriodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyPayroll Type.
        /// </summary>
        public static string PyPayrollTypeId {
            get {
                return ResourceManager.GetString("PyPayrollTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Form.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceId {
            get {
                return ResourceManager.GetString("SourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLkpId {
            get {
                return ResourceManager.GetString("StatusLkpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyPayroll Operations.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
